In [32]:

from IPython.core.display import HTML, display
from string import Template
import pandas as pd
import json, random

In [33]:
HTML("<script src='d3.js'></script>")

In [34]:
df = pd.read_csv("random.csv", sep = ";")

In [35]:
df.head()

   year  value  Unnamed: 2
0  2001      8         NaN
1  2002     83         NaN
2  2003     56         NaN
3  2004     75         NaN
4  2005     69         NaN

In [36]:
df.drop('Unnamed: 2',
  axis='columns', inplace=True)

In [37]:
df.head()

   year  value
0  2001      8
1  2002     83
2  2003     56
3  2004     75
4  2005     69

In [38]:
df_dict = df.to_dict(orient="records")
df_dict[:5]

[{'year': 2001, 'value': 8},
 {'year': 2002, 'value': 83},
 {'year': 2003, 'value': 56},
 {'year': 2004, 'value': 75},
 {'year': 2005, 'value': 69}]

In [39]:
js_text_template = Template('''
var margin = {top: 40, right: 40, bottom: 140, left: 80},
    width = 720 - margin.left - margin.right,
    height = 600 - margin.top - margin.bottom;

var x = d3.scale.linear().range([0, width]);

var y = d3.scale.linear().range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom")

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left")
    .ticks(10);

var color = d3.scale.category10();

var xAxis = d3.svg.axis()
.scale(x)
.orient("bottom");



var yAxis = d3.svg.axis()
.scale(y)
.orient("left");

var svg = d3.select("#$maid").append("svg")
.attr("width", width + margin.left+margin.left)
.attr("height", height + margin.top+margin.bottom)
.append("g")
.attr("transform","translate("+margin.left+","+margin.top+")")

var data = $python_data;



console.log(data)
x.domain(d3.extent(data,function(d) { return d.year;}));
y.domain(d3.extent(data,function(d) { return d.value}));


svg.append("g")
.attr("class","x axis")
.attr("transform","translate(20,"+height+")")
.call(xAxis)
.append("text")
.attr("transform","rotate(-90)")
.attr("class","label")
.attr("x",width)

svg.append("g")
.attr("class","y axis")
.call(yAxis)
.append("text")
.attr("transform","rotate(-90)")
.attr("class","label")
.attr("y",6)
.attr("dy",".71em")
.style("text-anchor","end")

svg.selectAll(".dot")
      .data(data)
    .enter().append("rect")
      .style("fill", "#E6E6FA")
      .attr("x", function(d) { return x(d.year); })
      .attr("width", 40)
      .attr("y", function(d) { return y(d.value); })
      .attr("height", function(d) { return height - y(d.value); });
      

step = 17  
var colors = ["#F08080", "#FFB6C1","LightYellow", "#E6E6FA", "#E0FFFF", "#FFDAB9", "#F08080", "#FFB6C1","LightYellow", "#E6E6FA", "#E0FFFF", "#FFDAB9"]
for (let i = 0; i < data.length - 2; i++){
      d = data[i]
      d2 = data[i + 1]
      
      console.log('d' , d)
      svg
        .append("line")        
        .attr("x1", step)
        .attr("y1", height - d.value/2 - 2)
        .attr("x2", step + 67)
        .attr("y2", height - d2.value/2 - 2 )
        .style("stroke", "blue") 
        .style("stroke-width", "3px") 
        step = step + 67
}


''');

In [40]:
html_template = Template('''
    <style>
    .dot{
        stroke: #000;
    }
    .legend{
        color:blue;
    }
    
    .axis path,
    .axis line{
        fill: none;
        shape-rendering:crispEdges;
    
    }
    </style>
    <div id="scatter-id"></div>
    <script>$js_text</script>
''')
js_text = js_text_template.substitute({
    "python_data":json.dumps(df_dict),
    "maid":"scatter-id"
})

In [41]:
HTML(html_template.substitute({'js_text':js_text}))